name: blooper_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  dartz: ^0.10.1
  http: ^0.13.4
  html: ^0.15.0
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: IRANSans
      fonts:
        - asset: 'assets/fonts/IRANSans.ttf'
    - family: Segoe_UI
      fonts:
        - asset: 'assets/fonts/Segoe UI.ttf'
          style: normal
        - asset: 'assets/fonts/Segoe UI Italic.ttf'
          style: italic
        - asset: 'assets/fonts/Segoe UI Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Segoe UI Bold Italic.ttf'
          style: italic
          weight: 700
